apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  accessModes: [ "ReadWriteOnce" ]

