---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: poder-sa
  namespace: default

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: poder-sa-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: poder-sa-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: poder-sa
    namespace: default
roleRef:
  kind: Role
  name: poder-sa-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: poder
  labels:
    app: poder
spec:
  serviceAccountName: poder-sa
  containers:
    - name: poder
      image: poder:v1.0

---
apiVersion: v1
kind: Service
metadata:
  name: poder
spec:
  selector:
    app: poder
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080